/twist_mux:
  ros__parameters:
    topics:
      keyboard:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 101
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 102
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
