TeleopTwistJoy:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 10.0

    enable_button: 7  # L2 shoulder button
    enable_turbo_button: 2  # L1 shoulder button
